-- =============================================================================
-- MIGRASI DATABASE: PRIMARY KEY MASTER DATA (TOKO, PEMASOK, DAPUR) DARI UUID KE BIGINT
-- =============================================================================
-- Jalankan skrip ini di Supabase SQL Editor:
-- Supabase Dashboard -> Project Anda -> SQL Editor -> Tempel & Klik "Run"
--
-- FITUR KEAMANAN MIGRASI:
-- 1. Aman dari data hilang / orphan (Data relasi dipetakan sebelum kolom UUID lama dihapus).
-- 2. Menggunakan BIGINT GENERATED BY DEFAULT AS IDENTITY (auto-increment integer 1, 2, 3...).
-- 3. Mengupdate kolom foreign key toko_id, pemasok_id, dapur_id di tabel pesanan jadi BIGINT.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- LANGKAH 1: HAPUS FOREIGN KEY CONSTRAINT LAMA YANG MERUJUK KE UUID
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT conname, conrelid::regclass AS tablename
        FROM pg_constraint
        WHERE confrelid IN ('public.toko'::regclass, 'public.pemasok'::regclass, 'public.dapur'::regclass)
    ) LOOP
        EXECUTE 'ALTER TABLE ' || r.tablename || ' DROP CONSTRAINT IF EXISTS ' || quote_ident(r.conname) || ' CASCADE;';
    END LOOP;
END $$;

-- -----------------------------------------------------------------------------
-- LANGKAH 2: BUAT KOLOM BARU new_id (BIGINT IDENTITY) PADA TABEL MASTER
-- -----------------------------------------------------------------------------
ALTER TABLE public.toko ADD COLUMN IF NOT EXISTS new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.pemasok ADD COLUMN IF NOT EXISTS new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.dapur ADD COLUMN IF NOT EXISTS new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- -----------------------------------------------------------------------------
-- LANGKAH 3: BUAT KOLOM TEMPORER FOREIGN KEY BIGINT DI TABEL PESANAN & TRANSAKSI
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'pesanan') THEN
    ALTER TABLE public.pesanan ADD COLUMN IF NOT EXISTS new_toko_id BIGINT;
    ALTER TABLE public.pesanan ADD COLUMN IF NOT EXISTS new_pemasok_id BIGINT;
    ALTER TABLE public.pesanan ADD COLUMN IF NOT EXISTS new_dapur_id BIGINT;

    -- Petakan relasi data existing dari UUID lama atau pencocokan nama
    -- 1. Toko
    UPDATE public.pesanan p
    SET new_toko_id = t.new_id
    FROM public.toko t
    WHERE (p.toko_id::text = t.id::text)
       OR (p.toko_id IS NULL AND (TRIM(p.toko) = t.nama OR TRIM(p.toko) ILIKE '%' || t.nama || '%'));

    -- 2. Pemasok
    UPDATE public.pesanan p
    SET new_pemasok_id = s.new_id
    FROM public.pemasok s
    WHERE (p.pemasok_id::text = s.id::text)
       OR (p.pemasok_id IS NULL AND TRIM(p.pemasok) = s.nama);

    -- 3. Dapur
    UPDATE public.pesanan p
    SET new_dapur_id = d.new_id
    FROM public.dapur d
    WHERE (p.dapur_id::text = d.id::text)
       OR (p.dapur_id IS NULL AND (TRIM(p.dapur) = d.nama OR TRIM(p.dapur) = 'Dapur ' || d.nama OR REPLACE(TRIM(p.dapur), 'Dapur ', '') = d.nama));
  END IF;

  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'transaksi') THEN
    ALTER TABLE public.transaksi ADD COLUMN IF NOT EXISTS new_toko_id BIGINT;
    ALTER TABLE public.transaksi ADD COLUMN IF NOT EXISTS new_pemasok_id BIGINT;
    ALTER TABLE public.transaksi ADD COLUMN IF NOT EXISTS new_dapur_id BIGINT;

    UPDATE public.transaksi tr
    SET new_toko_id = t.new_id
    FROM public.toko t
    WHERE (tr.toko_id::text = t.id::text) OR (tr.toko_id IS NULL AND TRIM(tr.toko) = t.nama);

    UPDATE public.transaksi tr
    SET new_pemasok_id = s.new_id
    FROM public.pemasok s
    WHERE (tr.pemasok_id::text = s.id::text) OR (tr.pemasok_id IS NULL AND TRIM(tr.pemasok) = s.nama);

    UPDATE public.transaksi tr
    SET new_dapur_id = d.new_id
    FROM public.dapur d
    WHERE (tr.dapur_id::text = d.id::text) OR (tr.dapur_id IS NULL AND (TRIM(tr.dapur) = d.nama OR TRIM(tr.dapur) = 'Dapur ' || d.nama));
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- LANGKAH 4: GANTI PRIMARY KEY TABEL MASTER DARI UUID KE BIGINT
-- -----------------------------------------------------------------------------

-- A. TOKO
ALTER TABLE public.toko DROP CONSTRAINT IF EXISTS toko_pkey CASCADE;
ALTER TABLE public.toko DROP COLUMN IF EXISTS id;
ALTER TABLE public.toko RENAME COLUMN new_id TO id;
ALTER TABLE public.toko ADD PRIMARY KEY (id);

-- B. PEMASOK
ALTER TABLE public.pemasok DROP CONSTRAINT IF EXISTS pemasok_pkey CASCADE;
ALTER TABLE public.pemasok DROP COLUMN IF EXISTS id;
ALTER TABLE public.pemasok RENAME COLUMN new_id TO id;
ALTER TABLE public.pemasok ADD PRIMARY KEY (id);

-- C. DAPUR
ALTER TABLE public.dapur DROP CONSTRAINT IF EXISTS dapur_pkey CASCADE;
ALTER TABLE public.dapur DROP COLUMN IF EXISTS id;
ALTER TABLE public.dapur RENAME COLUMN new_id TO id;
ALTER TABLE public.dapur ADD PRIMARY KEY (id);

-- -----------------------------------------------------------------------------
-- LANGKAH 5: GANTI KOLOM FK DI TABEL PESANAN & TRANSAKSI MENJADI BIGINT
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'pesanan') THEN
    ALTER TABLE public.pesanan DROP COLUMN IF EXISTS toko_id;
    ALTER TABLE public.pesanan RENAME COLUMN new_toko_id TO toko_id;

    ALTER TABLE public.pesanan DROP COLUMN IF EXISTS pemasok_id;
    ALTER TABLE public.pesanan RENAME COLUMN new_pemasok_id TO pemasok_id;

    ALTER TABLE public.pesanan DROP COLUMN IF EXISTS dapur_id;
    ALTER TABLE public.pesanan RENAME COLUMN new_dapur_id TO dapur_id;

    -- Pasang FK Baru merujuk ke BIGINT ID
    ALTER TABLE public.pesanan ADD CONSTRAINT fk_pesanan_toko FOREIGN KEY (toko_id) REFERENCES public.toko(id) ON DELETE SET NULL;
    ALTER TABLE public.pesanan ADD CONSTRAINT fk_pesanan_pemasok FOREIGN KEY (pemasok_id) REFERENCES public.pemasok(id) ON DELETE SET NULL;
    ALTER TABLE public.pesanan ADD CONSTRAINT fk_pesanan_dapur FOREIGN KEY (dapur_id) REFERENCES public.dapur(id) ON DELETE SET NULL;

    CREATE INDEX IF NOT EXISTS idx_pesanan_toko_id ON public.pesanan (toko_id);
    CREATE INDEX IF NOT EXISTS idx_pesanan_pemasok_id ON public.pesanan (pemasok_id);
    CREATE INDEX IF NOT EXISTS idx_pesanan_dapur_id ON public.pesanan (dapur_id);
  END IF;

  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'transaksi') THEN
    ALTER TABLE public.transaksi DROP COLUMN IF EXISTS toko_id;
    ALTER TABLE public.transaksi RENAME COLUMN new_toko_id TO toko_id;

    ALTER TABLE public.transaksi DROP COLUMN IF EXISTS pemasok_id;
    ALTER TABLE public.transaksi RENAME COLUMN new_pemasok_id TO pemasok_id;

    ALTER TABLE public.transaksi DROP COLUMN IF EXISTS dapur_id;
    ALTER TABLE public.transaksi RENAME COLUMN new_dapur_id TO dapur_id;

    ALTER TABLE public.transaksi ADD CONSTRAINT fk_transaksi_toko FOREIGN KEY (toko_id) REFERENCES public.toko(id) ON DELETE SET NULL;
    ALTER TABLE public.transaksi ADD CONSTRAINT fk_transaksi_pemasok FOREIGN KEY (pemasok_id) REFERENCES public.pemasok(id) ON DELETE SET NULL;
    ALTER TABLE public.transaksi ADD CONSTRAINT fk_transaksi_dapur FOREIGN KEY (dapur_id) REFERENCES public.dapur(id) ON DELETE SET NULL;

    CREATE INDEX IF NOT EXISTS idx_transaksi_toko_id ON public.transaksi (toko_id);
    CREATE INDEX IF NOT EXISTS idx_transaksi_pemasok_id ON public.transaksi (pemasok_id);
    CREATE INDEX IF NOT EXISTS idx_transaksi_dapur_id ON public.transaksi (dapur_id);
  END IF;
END $$;

COMMIT;
